# Generated by Django 5.2.9 on 2025-12-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='personnel_code',
            new_name='personel_code',
        ),
    ]
