# Generated by Django 5.2.9 on 2025-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_personnel_code_customuser_personel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personel_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
